name: Build & Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-26.04
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew build

      - run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: gh release upload "${{ github.event.release.tag_name }}" build/libs/*.jar --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}