name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew build

      - run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}